version: "3"
services:
    mysql:
        image: mysql:5.7
        ports:
            - "33061:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./database/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: kohinoor
            MYSQL_USER: mysql
            MYSQL_PASSWORD: secret
    nginx:
        restart: always
        depends_on:
            - backend
            - frontend
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80"
    backend:
        depends_on:
            - mysql
        build:
            dockerfile: Dockerfile.dev
            context: backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - "5000:5000"
        environment:
            - DB_USER=mysql
            - DB_HOST=mysql
            - DB_NAME=kohinoor
            - DB_PASSWORD=secret
            - DB_DIALECT=mysql
            - DB_PORT=3306
            - NODE_ENV=development
            - PORT=5000
            - JWT_SECRET=jwtsecret00
    frontend:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
